spring:
  application:
    name: cloud-service

server:
  port: 9001

###服务注册到eureka注册中心的地址
eureka:
  client:
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://pengwei:123456@192.168.99.189:9100/eureka/,http://pengwei:123456@192.168.99.189:9200/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 192.168.99.189
    instance-id: ${spring.application.name}###${server.port} #指定实例id
