###服务端口号
server:
  port: 9200

###服务名称
spring:
  application:
    name: app-eureka-center
    #添加安全认证依赖
  security:
    #开启基于HTTP basic的认证   高版本被丢弃
    #basic:
    #  enable: true
    user: #配置用户的账号信息
      name: pengwei
      password: 123456

eureka:
  instance:
    #注册中心地址
    hostname: 127.0.0.1
  ###客户端调用地址
  client:
    ###是否将自己注册到Eureka服务中,因为该应用本身就是注册中心，不需要再注册自己（集群的时候为true）
    registerWithEureka: true
    ###是否从Eureka中获取注册信息,因为自己为注册中心,不会在该应用中的检索服务信息（集群的时候为true）
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9100/eureka/

  ###测试环境、开发环境可以关闭自我保护机制，保证服务不可用时及时剔除  开启true / 关闭false
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 2000